version: '3'
services:
  cms-concept-backend:
    container_name: cms-concept-backend
    build: .
    image: cms-concept-backend:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: cms-concept-backendDB
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${NODE_ENV}
      HOST: 0.0.0.0
      PORT: 1337
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./package-lock.json:/opt/package-lock.json
      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - '1337:1337'
    networks:
      - cms-concept-backend
    depends_on:
      - cms-concept-backendDB
      
  cms-concept-backendDB:
    container_name: cms-concept-backendDB
    platform: linux/amd64
    restart: unless-stopped
    env_file: .env
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - cms-concept-backend-data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
    networks:
      - cms-concept-backend
      
  cms-concept-backendAdminer:
    container_name: cms-concept-backendAdminer
    image: adminer
    restart: unless-stopped
    ports:
      - '9090:8080'
    environment:
      - ADMINER_DEFAULT_SERVER=cms-concept-backendDB
    networks:
      - cms-concept-backend
    depends_on:
      - cms-concept-backendDB

  cms-concept-frontend:
    container_name: cms-concept-frontend
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ../cms-concept-frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: ["/bin/sh", "-c", "npm install --legacy-peer-deps && npm run dev"]
    networks:
      - cms-concept-backend
    depends_on:
      - cms-concept-backend

volumes:
  cms-concept-backend-data:

networks:
  cms-concept-backend:
    name: Cms-concept-backend
    driver: bridge
