services:
  cms-concept-backend-production:
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    image: cms-concept-backend-production
    ports:
      - "1340:1337"
    environment:
      NODE_ENV: production
    volumes:
      - ../../:/opt/app
      - /opt/app/node_modules
